#!/bin/bash

alias modules="modules.sh"
alias mqtt_servers="mqtt_servers.sh"
alias get_mqtt_servers="get_mqtt_servers.sh"
alias modules="modules.sh"
alias e2encs="e2encs.sh"
alias networks="networks.sh"
alias ncs="ncs.sh"
alias tcs="tcs.sh"
alias service="service.sh"
alias get_entities="get_entities.sh"
alias get_modules="get_modules.sh"
alias get_hub_module="get_hub_module.sh"
alias get_leaf_modules="get_leaf_modules.sh"
alias get_reachable_modules="get_reachable_modules.sh"
alias get_networks="get_networks.sh"
alias get_tcs="get_transport_capacities.sh"
alias get_tcs_capacity_links="get_tcs_capacity_links.sh"
alias get_tc_endpoints="get_tc_endpoints.sh"
alias get_hosts="get_hosts.sh"
alias get_hosts_port="get_hosts_port.sh"
alias get_acs="get_acs.sh"
alias get_carriers="get_carriers.sh"
alias get_dscgs="get_dscgs.sh"
alias get_dscs="get_dscs.sh"
alias get_ethernet_clients="get_ethernet_clients.sh"
alias get_lcs="get_lcs.sh"
alias get_line_ptps="get_line_ptps.sh"
alias get_otus="get_otus.sh"
alias get_odus="get_odus.sh"
alias get_ncs="get_ncs.sh"
alias get_ncs_lcs="get_ncs_lcs.sh"
alias get_ncs_acs="get_ncs_acs.sh"
alias get_ndus="get_ndus.sh"
alias get_ndu_eclients="get_ndu_eclients.sh"
alias get_ndu_carriers="get_ndu_carriers.sh"
alias get_ndu_edfas="get_ndu_edfas.sh"
alias get_ndu_lcs="get_ndu_lcs.sh"
alias get_ndu_ndu_line_ptps="get_ndu_ndu_line_ptps.sh"
alias get_ndu_otus="get_ndu_otus.sh"
alias get_ndu_odus="get_ndu_odus.sh"
alias get_ndu_pol_ptps="get_ndu_pol_ptps.sh"
alias get_ndu_ports="get_ndu_ports.sh"
alias get_ndu_toms="get_ndu_toms.sh"
alias get_ndu_trib_ptps="get_ndu_trib_ptps.sh"
alias get_ndu_voas="get_ndu_voas.sh"
alias get_ndu_xrs="get_ndu_xrs.sh"
alias tfc='rm *.tfstate .terraform.lock*'
alias tfi='terraform init'
alias tfa='terraform apply'
alias tfp='terraform plan'
alias tfaa='terraform apply - auto-approve'
alias tfd='terraform delete'
alias tfda='terraform delete -auto-approve'A
alias tcsa='tcs.sh apply'
alias tcsp='tcs.sh plan'
alias tcsd='tcs.sh delete'
alias tcsi='tcs.sh init'
alias ncsd='ncs.sh delete'
alias ncsp='ncs.sh plan'
alias ncsi='ncs.sh init'
alias netd='networks.sh delete'
alias neta='networks.sh apply'
alias netp='networks.sh plan'
alias neti='networks.sh init'
alias ncsa='ncs.sh apply'
alias e2encsa='e2encs.sh apply'
alias e2encsd='e2encs.sh delete'
alias e2encsp='e2encs.sh plan'
alias e2encsi='e2encs.sh init'